Repository namekeptanonymous/cosc441-group-10, pull requests merged in 2024-11, with the labels that each got.

#5 Added keys to the StudyScene
  Assets/Scenes/StudyScene.unity
  ProjectSettings/TagManager.asset
Labels: UI

#7 Added basic Cursor behaviour + clickable keys + cleaned up StudyScene
  .gitignore
  Assets/Design_webOSTV60_VirtualKeyboard_URL_ro1dmu.jpg
  Assets/Prefabs/Key.prefab
  Assets/Scenes/StudyScene.unity
  Assets/Scripts/Cursor.cs
  Assets/Scripts/Key.cs
  Assets/Scripts/KeyboardKey.cs
  Assets/Scripts/KeyboardKey.cs.meta
  Assets/Textures.meta
  Assets/Textures/Design_webOSTV60_VirtualKeyboard_URL_ro1dmu.png
  Assets/Textures/Design_webOSTV60_VirtualKeyboard_URL_ro1dmu.png.meta
Labels: technical, UI

#9 added snapping functionality
  Assets/Scenes/StudyScene.unity
  Assets/Scripts/Cursor.cs
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
Labels: technical

#16 Adding Study Behavior (full study functionality)
  .gitignore
  Assets/Scenes/MainMenu.unity
  Assets/Scenes/StudyScene.unity
  Assets/Scripts/Cursor.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/KeyboardKey.cs
  Assets/Scripts/StudyBehavior.cs
Labels: technical, UI
